name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies (if present)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Lint (flake8) – safe defaults; won't fail build if not present
      - name: Lint with flake8 (optional)
        run: |
          pip install flake8 || true
          flake8 . || true

      # Unit tests (if the repo has any); harmless if missing
      - name: Run tests (pytest) (optional)
        run: |
          pip install pytest || true
          pytest -q || true
